### PR TITLE
Add eslint

### PR DESCRIPTION
**Pull request by sanny-io**
It's missing the CI/CD functionality for now, but I will do that afterwards.

### CODE REVIEW

**Comment by sanny-io** [comment]
It's missing the CI/CD functionality for now, but I will do that separately.

**Review by dishwasher-detergent — COMMENTED** [review]
Looks good

**Review by dishwasher-detergent — APPROVED** [review]

**Comment by probablyArth** [comment]
lgtm, can you run eslint --fix on the whole project, so the whole codebase is on the same page?

**Comment by sanny-io** [comment]
@probablyArth I have done so now, and there are no changes eslint is making. It's definitely working, though. If I place some double quotes or semicolons, it fixes them, but there are none existing in the project at the moment.

**Pull request merged**
